/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cliente;

import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import servidor.ServidorRemoto;

/**
 *
 * @author hugos
 */
public class ClienteGUI extends javax.swing.JFrame {

    private ServidorRemoto servidor;
    
    public ClienteGUI() {
        initComponents();
        conectarServidor();
    }
    
    public javax.swing.JTextField getTextRefugio() { return refugioTextField; }
    
    public javax.swing.JTextField getTextRiesgo1H() { return riesgo1HTextField; }
    public javax.swing.JTextField getTextRiesgo2H() { return riesgo2HTextField; }
    public javax.swing.JTextField getTextRiesgo3H() { return riesgo3HTextField; }
    public javax.swing.JTextField getTextRiesgo4H() { return riesgo4HTextField; }
    
    public javax.swing.JTextField getTextRiesgo1Z() { return riesgo1ZTextField; }
    public javax.swing.JTextField getTextRiesgo2Z() { return riesgo2ZTextField; }
    public javax.swing.JTextField getTextRiesgo3Z() { return riesgo3ZTextField; }
    public javax.swing.JTextField getTextRiesgo4Z() { return riesgo4ZTextField; }
    
    public javax.swing.JTextField getTextTunel1() { return tunel1TextField; }
    public javax.swing.JTextField getTextTunel2() { return tunel2TextField; }
    public javax.swing.JTextField getTextTunel3() { return tunel3TextField; }
    public javax.swing.JTextField getTextTunel4() { return tunel4TextField; }

    public javax.swing.JTextArea getTopZombisTextArea() { return topZombisTextArea;}
    
    private void conectarServidor(){
        try{
            servidor = (ServidorRemoto) Naming.lookup("//localhost/objeto");
            System.out.println("Cliente conectando al servidor");
        } catch (Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al conectar al servidor", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public static void main (String[] args) throws RemoteException{
        new ClienteGUI().setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        refugioTextField = new javax.swing.JTextField();
        tunel1TextField = new javax.swing.JTextField();
        riesgo1HTextField = new javax.swing.JTextField();
        riesgo1ZTextField = new javax.swing.JTextField();
        riesgo2ZTextField = new javax.swing.JTextField();
        riesgo3ZTextField = new javax.swing.JTextField();
        riesgo4ZTextField = new javax.swing.JTextField();
        riesgo4HTextField = new javax.swing.JTextField();
        riesgo3HTextField = new javax.swing.JTextField();
        riesgo2HTextField = new javax.swing.JTextField();
        tunel4TextField = new javax.swing.JTextField();
        tunel3TextField = new javax.swing.JTextField();
        tunel2TextField = new javax.swing.JTextField();
        pauseResumeButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        topZombisTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Humanos en el refugio");

        jLabel2.setText("Humanos en los túneles");

        jLabel3.setText("Zombis en las zonas de riesgo");

        jLabel4.setText("Humanos en las zonas de riesgo");

        jLabel5.setText("Zombis mas letales");

        refugioTextField.setEditable(false);
        refugioTextField.setText("jTextField1");
        refugioTextField.setMaximumSize(new java.awt.Dimension(74, 26));
        refugioTextField.setMinimumSize(new java.awt.Dimension(74, 26));

        tunel1TextField.setEditable(false);
        tunel1TextField.setText("jTextField2");
        tunel1TextField.setMaximumSize(new java.awt.Dimension(74, 26));
        tunel1TextField.setMinimumSize(new java.awt.Dimension(74, 26));

        riesgo1HTextField.setEditable(false);
        riesgo1HTextField.setText("jTextField3");
        riesgo1HTextField.setMaximumSize(new java.awt.Dimension(74, 26));
        riesgo1HTextField.setMinimumSize(new java.awt.Dimension(74, 26));

        riesgo1ZTextField.setEditable(false);
        riesgo1ZTextField.setText("jTextField4");
        riesgo1ZTextField.setMaximumSize(new java.awt.Dimension(74, 26));
        riesgo1ZTextField.setMinimumSize(new java.awt.Dimension(74, 26));

        riesgo2ZTextField.setEditable(false);
        riesgo2ZTextField.setText("jTextField5");
        riesgo2ZTextField.setMaximumSize(new java.awt.Dimension(74, 26));
        riesgo2ZTextField.setMinimumSize(new java.awt.Dimension(74, 26));

        riesgo3ZTextField.setEditable(false);
        riesgo3ZTextField.setText("jTextField6");
        riesgo3ZTextField.setMaximumSize(new java.awt.Dimension(74, 26));
        riesgo3ZTextField.setMinimumSize(new java.awt.Dimension(74, 26));

        riesgo4ZTextField.setEditable(false);
        riesgo4ZTextField.setText("jTextField7");
        riesgo4ZTextField.setMaximumSize(new java.awt.Dimension(74, 26));
        riesgo4ZTextField.setMinimumSize(new java.awt.Dimension(74, 26));

        riesgo4HTextField.setEditable(false);
        riesgo4HTextField.setText("jTextField7");
        riesgo4HTextField.setMaximumSize(new java.awt.Dimension(74, 26));
        riesgo4HTextField.setMinimumSize(new java.awt.Dimension(74, 26));

        riesgo3HTextField.setEditable(false);
        riesgo3HTextField.setText("jTextField6");
        riesgo3HTextField.setMaximumSize(new java.awt.Dimension(74, 26));
        riesgo3HTextField.setMinimumSize(new java.awt.Dimension(74, 26));

        riesgo2HTextField.setEditable(false);
        riesgo2HTextField.setText("jTextField5");
        riesgo2HTextField.setMaximumSize(new java.awt.Dimension(74, 26));
        riesgo2HTextField.setMinimumSize(new java.awt.Dimension(74, 26));

        tunel4TextField.setEditable(false);
        tunel4TextField.setText("jTextField7");
        tunel4TextField.setMaximumSize(new java.awt.Dimension(74, 26));
        tunel4TextField.setMinimumSize(new java.awt.Dimension(74, 26));

        tunel3TextField.setEditable(false);
        tunel3TextField.setText("jTextField6");
        tunel3TextField.setMaximumSize(new java.awt.Dimension(74, 26));
        tunel3TextField.setMinimumSize(new java.awt.Dimension(74, 26));

        tunel2TextField.setEditable(false);
        tunel2TextField.setText("jTextField5");
        tunel2TextField.setMaximumSize(new java.awt.Dimension(74, 26));
        tunel2TextField.setMinimumSize(new java.awt.Dimension(74, 26));

        pauseResumeButton.setText("jButton1");
        pauseResumeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseResumeButtonActionPerformed(evt);
            }
        });

        topZombisTextArea.setColumns(20);
        topZombisTextArea.setRows(5);
        jScrollPane1.setViewportView(topZombisTextArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(riesgo1HTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(riesgo2HTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(riesgo3HTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(riesgo4HTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tunel1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tunel2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tunel3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tunel4TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(refugioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(riesgo1ZTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(riesgo2ZTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(riesgo3ZTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(139, 139, 139)
                                        .addComponent(pauseResumeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(riesgo4ZTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(refugioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tunel1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tunel2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tunel3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tunel4TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(riesgo1HTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(riesgo2HTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(riesgo3HTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(riesgo4HTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(riesgo1ZTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(riesgo2ZTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(riesgo3ZTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(riesgo4ZTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jLabel5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pauseResumeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(38, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pauseResumeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseResumeButtonActionPerformed
        try {
            // TODO add your handling code here:
            servidor.togglePausa();
        } catch (RemoteException ex) {}
    }//GEN-LAST:event_pauseResumeButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton pauseResumeButton;
    private javax.swing.JTextField refugioTextField;
    private javax.swing.JTextField riesgo1HTextField;
    private javax.swing.JTextField riesgo1ZTextField;
    private javax.swing.JTextField riesgo2HTextField;
    private javax.swing.JTextField riesgo2ZTextField;
    private javax.swing.JTextField riesgo3HTextField;
    private javax.swing.JTextField riesgo3ZTextField;
    private javax.swing.JTextField riesgo4HTextField;
    private javax.swing.JTextField riesgo4ZTextField;
    private javax.swing.JTextArea topZombisTextArea;
    private javax.swing.JTextField tunel1TextField;
    private javax.swing.JTextField tunel2TextField;
    private javax.swing.JTextField tunel3TextField;
    private javax.swing.JTextField tunel4TextField;
    // End of variables declaration//GEN-END:variables
}
