/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package programacion.avanzada.apocalipsiszombi;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author Usuario
 */
public class MonitorSistema extends javax.swing.JFrame {

    /**
     * Creates new form MonitorSistema
     */
    private MapaZonas mapa;
        
    public MonitorSistema(){
        initComponents();
        actualizarTodas();
    }
    
    public MonitorSistema(MapaZonas mapa) {
        initComponents();
        this.mapa = mapa;
        actualizarTodas();
    }
    
    public void actualizarTodas() {
        actualizarInformacion(Zona.RIESGO_1, jScrollPaneInsegura1);
        actualizarInformacion(Zona.RIESGO_2, jScrollPaneInsegura2);
        actualizarInformacion(Zona.RIESGO_3, jScrollPaneInsegura3);
        actualizarInformacion(Zona.RIESGO_4, jScrollPaneInsegura4);

        actualizarInformacion(Zona.TUNEL_1, jScrollPaneTunel1);
        actualizarInformacion(Zona.TUNEL_2, jScrollPaneTunel2);
        actualizarInformacion(Zona.TUNEL_3, jScrollPaneTunel3);
        actualizarInformacion(Zona.TUNEL_4, jScrollPaneTunel4);

        actualizarInformacion(Zona.DESCANSO, scrollPaneDescanso);
        actualizarInformacion(Zona.COMEDOR, scrollPaneComedor);
        actualizarInformacion(Zona.ZONA_COMUN, scrollPaneComun);
    }
    
    public void actualizarInformacion(Zona zona, JScrollPane scrollPane) {
        JPanel mainPanel = new JPanel();
        mainPanel.setLayout(new BoxLayout(mainPanel, BoxLayout.Y_AXIS));
        mainPanel.setBackground(Color.WHITE);

        // Título de la zona
        JPanel titlePanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
        titlePanel.setBackground(Color.LIGHT_GRAY);
        JLabel titleLabel = new JLabel(zona.toString());
        titlePanel.add(titleLabel);
        mainPanel.add(titlePanel);

        // Humanos en la zona
        List<Humano> humanos = mapa.humanosEnZona(zona);
        if (!humanos.isEmpty()) {
            JPanel humanTitlePanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
            humanTitlePanel.add(new JLabel("Humanos:"));
            mainPanel.add(humanTitlePanel);

            for (Humano h : humanos) {
                JPanel itemPanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
                itemPanel.setBackground(Color.WHITE);
                itemPanel.add(new JLabel(h.getIdHumano()));
                mainPanel.add(itemPanel);
            }
        }

        // Zombis en la zona (solo para zonas de riesgo)
        if (zona.name().startsWith("RIESGO")) {
            List<Zombi> zombis = mapa.zombisEnZona(zona);
            if (!zombis.isEmpty()) {
                JPanel zombieTitlePanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
                zombieTitlePanel.add(new JLabel("Zombis:"));
                mainPanel.add(zombieTitlePanel);

                for (Zombi z : zombis) {
                    JPanel itemPanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
                    itemPanel.setBackground(new Color(255, 200, 200)); // Rojo claro
                    itemPanel.add(new JLabel(z.getIdZombi()));
                    mainPanel.add(itemPanel);
                }
            }
        }

        // Si no hay nadie
        if (humanos.isEmpty() && (!zona.name().startsWith("RIESGO") || mapa.zombisEnZona(zona).isEmpty())) {
            JPanel emptyPanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
            emptyPanel.add(new JLabel("Vacía"));
            mainPanel.add(emptyPanel);
        }

        scrollPane.setViewportView(mainPanel);
        scrollPane.revalidate();
        scrollPane.repaint();
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        PanelRefugio = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        SigTunel = new javax.swing.JButton();
        scrollPaneComedor = new javax.swing.JScrollPane();
        scrollPaneDescanso = new javax.swing.JScrollPane();
        scrollPaneComun = new javax.swing.JScrollPane();
        PanelTunel = new javax.swing.JPanel();
        SigInsegura = new javax.swing.JButton();
        AtrasRefugio = new javax.swing.JButton();
        jScrollPaneTunel2 = new javax.swing.JScrollPane();
        jScrollPaneTunel1 = new javax.swing.JScrollPane();
        jScrollPaneTunel3 = new javax.swing.JScrollPane();
        jScrollPaneTunel4 = new javax.swing.JScrollPane();
        jLabel7 = new javax.swing.JLabel();
        PanelZonaInsegura = new javax.swing.JPanel();
        AtrasTunel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPaneInsegura1 = new javax.swing.JScrollPane();
        jScrollPaneInsegura2 = new javax.swing.JScrollPane();
        jScrollPaneInsegura3 = new javax.swing.JScrollPane();
        jScrollPaneInsegura4 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("refugio");

        SigTunel.setText("Siguiente");
        SigTunel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SigTunelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelRefugioLayout = new javax.swing.GroupLayout(PanelRefugio);
        PanelRefugio.setLayout(PanelRefugioLayout);
        PanelRefugioLayout.setHorizontalGroup(
            PanelRefugioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRefugioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SigTunel)
                .addContainerGap())
            .addGroup(PanelRefugioLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(scrollPaneComedor, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(scrollPaneDescanso, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(scrollPaneComun, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addGroup(PanelRefugioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelRefugioLayout.createSequentialGroup()
                    .addGap(408, 408, 408)
                    .addComponent(jLabel4)
                    .addContainerGap(562, Short.MAX_VALUE)))
        );
        PanelRefugioLayout.setVerticalGroup(
            PanelRefugioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRefugioLayout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(PanelRefugioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrollPaneComedor, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrollPaneDescanso, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrollPaneComun, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(SigTunel)
                .addContainerGap())
            .addGroup(PanelRefugioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelRefugioLayout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(jLabel4)
                    .addContainerGap(464, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("tab1", PanelRefugio);

        SigInsegura.setText("Siguiente");
        SigInsegura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SigInseguraActionPerformed(evt);
            }
        });

        AtrasRefugio.setText("Atrás");
        AtrasRefugio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasRefugioActionPerformed(evt);
            }
        });

        jLabel7.setText("Túneles");

        javax.swing.GroupLayout PanelTunelLayout = new javax.swing.GroupLayout(PanelTunel);
        PanelTunel.setLayout(PanelTunelLayout);
        PanelTunelLayout.setHorizontalGroup(
            PanelTunelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTunelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AtrasRefugio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SigInsegura)
                .addContainerGap())
            .addGroup(PanelTunelLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jScrollPaneTunel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jScrollPaneTunel2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jScrollPaneTunel4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(jScrollPaneTunel3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(PanelTunelLayout.createSequentialGroup()
                .addGap(478, 478, 478)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelTunelLayout.setVerticalGroup(
            PanelTunelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTunelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(PanelTunelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelTunelLayout.createSequentialGroup()
                        .addGap(0, 72, Short.MAX_VALUE)
                        .addGroup(PanelTunelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPaneTunel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelTunelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPaneTunel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPaneTunel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PanelTunelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPaneTunel2, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(PanelTunelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SigInsegura)
                    .addComponent(AtrasRefugio)))
        );

        jTabbedPane1.addTab("tab2", PanelTunel);

        AtrasTunel.setText("Atrás");
        AtrasTunel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasTunelActionPerformed(evt);
            }
        });

        jLabel3.setText("Zona Insegura");

        javax.swing.GroupLayout PanelZonaInseguraLayout = new javax.swing.GroupLayout(PanelZonaInsegura);
        PanelZonaInsegura.setLayout(PanelZonaInseguraLayout);
        PanelZonaInseguraLayout.setHorizontalGroup(
            PanelZonaInseguraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelZonaInseguraLayout.createSequentialGroup()
                .addGroup(PanelZonaInseguraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelZonaInseguraLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AtrasTunel))
                    .addGroup(PanelZonaInseguraLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jScrollPaneInsegura1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPaneInsegura2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(jScrollPaneInsegura3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(jScrollPaneInsegura4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
            .addGroup(PanelZonaInseguraLayout.createSequentialGroup()
                .addGap(457, 457, 457)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelZonaInseguraLayout.setVerticalGroup(
            PanelZonaInseguraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelZonaInseguraLayout.createSequentialGroup()
                .addGroup(PanelZonaInseguraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelZonaInseguraLayout.createSequentialGroup()
                        .addGap(24, 104, Short.MAX_VALUE)
                        .addGroup(PanelZonaInseguraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPaneInsegura1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelZonaInseguraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPaneInsegura4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPaneInsegura3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PanelZonaInseguraLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPaneInsegura2, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(AtrasTunel)
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab3", PanelZonaInsegura);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, -1, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SigTunelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SigTunelActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_SigTunelActionPerformed

    private void SigInseguraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SigInseguraActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_SigInseguraActionPerformed

    private void AtrasRefugioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasRefugioActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_AtrasRefugioActionPerformed

    private void AtrasTunelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasTunelActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_AtrasTunelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MonitorSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MonitorSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MonitorSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MonitorSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MonitorSistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AtrasRefugio;
    private javax.swing.JButton AtrasTunel;
    private javax.swing.JPanel PanelRefugio;
    private javax.swing.JPanel PanelTunel;
    private javax.swing.JPanel PanelZonaInsegura;
    private javax.swing.JButton SigInsegura;
    private javax.swing.JButton SigTunel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPaneInsegura1;
    private javax.swing.JScrollPane jScrollPaneInsegura2;
    private javax.swing.JScrollPane jScrollPaneInsegura3;
    private javax.swing.JScrollPane jScrollPaneInsegura4;
    private javax.swing.JScrollPane jScrollPaneTunel1;
    private javax.swing.JScrollPane jScrollPaneTunel2;
    private javax.swing.JScrollPane jScrollPaneTunel3;
    private javax.swing.JScrollPane jScrollPaneTunel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JScrollPane scrollPaneComedor;
    private javax.swing.JScrollPane scrollPaneComun;
    private javax.swing.JScrollPane scrollPaneDescanso;
    // End of variables declaration//GEN-END:variables
}
