/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package programacion.avanzada.apocalipsiszombi;

/**
 *
 * @author adria
 */
public class MonitorSistema2 extends javax.swing.JFrame {

    /**
     * Creates new form MonitorSistema2
     */
    public MonitorSistema2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        scrollDescanso = new javax.swing.JScrollPane();
        scrollComedor = new javax.swing.JScrollPane();
        scrollComun = new javax.swing.JScrollPane();
        refugioTunel1 = new javax.swing.JScrollPane();
        refugioTunel2 = new javax.swing.JScrollPane();
        refugioTunel3 = new javax.swing.JScrollPane();
        riesgoTunel1 = new javax.swing.JScrollPane();
        riesgoHumanos1 = new javax.swing.JScrollPane();
        riesgoTunel2 = new javax.swing.JScrollPane();
        riesgoTunel3 = new javax.swing.JScrollPane();
        riesgoHumanos2 = new javax.swing.JScrollPane();
        riesgoHumanos3 = new javax.swing.JScrollPane();
        riesgoZombi3 = new javax.swing.JScrollPane();
        riesgoZombi2 = new javax.swing.JScrollPane();
        riesgoZombi1 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        contadorComida = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tunel1 = new javax.swing.JTextField();
        tunel2 = new javax.swing.JTextField();
        tunel3 = new javax.swing.JTextField();
        refugioTunel4 = new javax.swing.JScrollPane();
        riesgoTunel4 = new javax.swing.JScrollPane();
        tunel4 = new javax.swing.JTextField();
        riesgoHumanos4 = new javax.swing.JScrollPane();
        riesgoZombi4 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Apocalipsis Zombie");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(scrollDescanso, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 240, 100));
        jPanel1.add(scrollComedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 150, 100));
        jPanel1.add(scrollComun, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, 240, 100));
        jPanel1.add(refugioTunel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 100, 100));
        jPanel1.add(refugioTunel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 100, 100));
        jPanel1.add(refugioTunel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 460, 100, 100));
        jPanel1.add(riesgoTunel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 140, 100, 100));
        jPanel1.add(riesgoHumanos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 140, 110, 100));
        jPanel1.add(riesgoTunel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 290, 100, 100));
        jPanel1.add(riesgoTunel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 460, 100, 100));
        jPanel1.add(riesgoHumanos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 290, 110, 100));
        jPanel1.add(riesgoHumanos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 460, 110, 100));
        jPanel1.add(riesgoZombi3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 460, 110, 100));
        jPanel1.add(riesgoZombi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 290, 110, 100));
        jPanel1.add(riesgoZombi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 140, 110, 100));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Refugio");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 41, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Túneles");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(621, 41, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Zona de riesgo");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1058, 41, -1, -1));

        jButton2.setText("Parar");
        jButton2.setActionCommand("pararButton");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 740, -1, -1));

        contadorComida.setText("jTextField1");
        contadorComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contadorComidaActionPerformed(evt);
            }
        });
        jPanel1.add(contadorComida, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, -1, -1));

        jLabel4.setText("Comida");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, -1, -1));

        tunel1.setText("jTextField1");
        jPanel1.add(tunel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, -1, -1));

        tunel2.setText("jTextField2");
        jPanel1.add(tunel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, -1, -1));

        tunel3.setText("jTextField3");
        jPanel1.add(tunel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 500, -1, -1));
        jPanel1.add(refugioTunel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 610, 100, 100));
        jPanel1.add(riesgoTunel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 610, 100, 100));

        tunel4.setText("jTextField4");
        jPanel1.add(tunel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 650, -1, -1));
        jPanel1.add(riesgoHumanos4, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 580, 110, 100));
        jPanel1.add(riesgoZombi4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 580, 110, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1323, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contadorComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contadorComidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contadorComidaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MonitorSistema2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MonitorSistema2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MonitorSistema2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MonitorSistema2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MonitorSistema2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField contadorComida;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane refugioTunel1;
    private javax.swing.JScrollPane refugioTunel2;
    private javax.swing.JScrollPane refugioTunel3;
    private javax.swing.JScrollPane refugioTunel4;
    private javax.swing.JScrollPane riesgoHumanos1;
    private javax.swing.JScrollPane riesgoHumanos2;
    private javax.swing.JScrollPane riesgoHumanos3;
    private javax.swing.JScrollPane riesgoHumanos4;
    private javax.swing.JScrollPane riesgoTunel1;
    private javax.swing.JScrollPane riesgoTunel2;
    private javax.swing.JScrollPane riesgoTunel3;
    private javax.swing.JScrollPane riesgoTunel4;
    private javax.swing.JScrollPane riesgoZombi1;
    private javax.swing.JScrollPane riesgoZombi2;
    private javax.swing.JScrollPane riesgoZombi3;
    private javax.swing.JScrollPane riesgoZombi4;
    private javax.swing.JScrollPane scrollComedor;
    private javax.swing.JScrollPane scrollComun;
    private javax.swing.JScrollPane scrollDescanso;
    private javax.swing.JTextField tunel1;
    private javax.swing.JTextField tunel2;
    private javax.swing.JTextField tunel3;
    private javax.swing.JTextField tunel4;
    // End of variables declaration//GEN-END:variables
}
