/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package programacion.avanzada.apocalipsiszombi;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author Usuario
 */
public class MonitorSistema extends javax.swing.JFrame {

    /**
     * Creates new form MonitorSistema
     */
    private MapaZonas mapa;
    
    public MonitorSistema(){
        initComponents();
        actualizarTodas();
    }
    
    public MonitorSistema(MapaZonas mapa) {
        initComponents();
        this.mapa = mapa;
        actualizarTodas();
    }
    
    public void actualizarTodas() {
        actualizarInformacion(Zona.RIESGO_1, jScrollPaneInsegura1);
        actualizarInformacion(Zona.RIESGO_2, jScrollPaneInsegura2);
        actualizarInformacion(Zona.RIESGO_3, jScrollPaneInsegura3);
        actualizarInformacion(Zona.RIESGO_4, jScrollPaneInsegura4);

        actualizarInformacion(Zona.TUNEL_1, jScrollPaneTunel1);
        actualizarInformacion(Zona.TUNEL_2, jScrollPaneTunel2);
        actualizarInformacion(Zona.TUNEL_3, jScrollPaneTunel3);
        actualizarInformacion(Zona.TUNEL_4, jScrollPaneTunel4);

        actualizarInformacion(Zona.DESCANSO, scrollPaneDescanso);
        actualizarInformacion(Zona.COMEDOR, scrollPaneComedor);
        actualizarInformacion(Zona.ZONA_COMUN, scrollPaneComun);
    }
    
    public void actualizarInformacion(Zona zona, JScrollPane scrollPane) {
        JPanel mainPanel = new JPanel();
        mainPanel.setLayout(new BoxLayout(mainPanel, BoxLayout.Y_AXIS));
        mainPanel.setBackground(Color.WHITE);

        if (mapa == null) {
            JPanel itemPanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
            itemPanel.setBackground(Color.WHITE);
            itemPanel.setBorder(BorderFactory.createEmptyBorder(5, 10, 5, 10));

            JLabel label = new JLabel(zona.name());
            itemPanel.add(label);

            mainPanel.add(itemPanel);
        } else {
            // Mostrar humanos
            List<Humano> humanos = mapa.humanosEnZona(zona);
            for (Humano h : humanos) {
                JPanel itemPanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
                itemPanel.setBackground(Color.WHITE);
                itemPanel.setBorder(BorderFactory.createEmptyBorder(5, 10, 5, 10));

                JLabel humanoLabel = new JLabel("[" + h.getIdHumano() + "]");
                itemPanel.add(humanoLabel);

                mainPanel.add(itemPanel);
                mainPanel.add(Box.createRigidArea(new Dimension(0, 5)));
            }

            // Mostrar zombis solo si la zona es de riesgo
            if (zona.name().startsWith("RIESGO")) {
                List<Zombi> zombis = mapa.zombisEnZona(zona);
                for (Zombi z : zombis) {
                    JPanel itemPanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
                    itemPanel.setBackground(new Color(255, 240, 240)); // fondo suave rojo para zombis
                    itemPanel.setBorder(BorderFactory.createEmptyBorder(5, 10, 5, 10));

                    JLabel zombiLabel = new JLabel("[" + z.getIdZombi() + "]");
                    itemPanel.add(zombiLabel);

                    mainPanel.add(itemPanel);
                    mainPanel.add(Box.createRigidArea(new Dimension(0, 5)));
                }
            }
        }

        // Actualizar el scrollPane con el nuevo contenido
        scrollPane.setViewportView(mainPanel);
        scrollPane.revalidate();
        scrollPane.repaint();
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        PanelRefugio = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        SigTunel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        scrollPaneComedor = new javax.swing.JScrollPane();
        jLabel5 = new javax.swing.JLabel();
        scrollPaneDescanso = new javax.swing.JScrollPane();
        jLabel6 = new javax.swing.JLabel();
        scrollPaneComun = new javax.swing.JScrollPane();
        PanelTunel = new javax.swing.JPanel();
        SigInsegura = new javax.swing.JButton();
        AtrasRefugio = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPaneTunel2 = new javax.swing.JScrollPane();
        jScrollPaneTunel1 = new javax.swing.JScrollPane();
        jScrollPaneTunel3 = new javax.swing.JScrollPane();
        jScrollPaneTunel4 = new javax.swing.JScrollPane();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        PanelZonaInsegura = new javax.swing.JPanel();
        AtrasTunel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPaneInsegura1 = new javax.swing.JScrollPane();
        jLabel11 = new javax.swing.JLabel();
        jScrollPaneInsegura2 = new javax.swing.JScrollPane();
        jLabel12 = new javax.swing.JLabel();
        jScrollPaneInsegura3 = new javax.swing.JScrollPane();
        jLabel13 = new javax.swing.JLabel();
        jScrollPaneInsegura4 = new javax.swing.JScrollPane();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("refugio");

        SigTunel.setText("Siguiente");
        SigTunel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SigTunelActionPerformed(evt);
            }
        });

        jLabel1.setText("Comedor");

        jLabel5.setText("Zona de descanso");

        jLabel6.setText("Zona común");

        javax.swing.GroupLayout PanelRefugioLayout = new javax.swing.GroupLayout(PanelRefugio);
        PanelRefugio.setLayout(PanelRefugioLayout);
        PanelRefugioLayout.setHorizontalGroup(
            PanelRefugioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRefugioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SigTunel)
                .addContainerGap())
            .addGroup(PanelRefugioLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(PanelRefugioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneComedor, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelRefugioLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addGroup(PanelRefugioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelRefugioLayout.createSequentialGroup()
                        .addComponent(scrollPaneDescanso, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRefugioLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(93, 93, 93)))
                .addGroup(PanelRefugioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneComun, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelRefugioLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel6)))
                .addContainerGap(193, Short.MAX_VALUE))
            .addGroup(PanelRefugioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelRefugioLayout.createSequentialGroup()
                    .addGap(408, 408, 408)
                    .addComponent(jLabel4)
                    .addContainerGap(562, Short.MAX_VALUE)))
        );
        PanelRefugioLayout.setVerticalGroup(
            PanelRefugioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRefugioLayout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(PanelRefugioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelRefugioLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollPaneComedor, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelRefugioLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollPaneDescanso, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelRefugioLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollPaneComun, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(SigTunel)
                .addContainerGap())
            .addGroup(PanelRefugioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelRefugioLayout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(jLabel4)
                    .addContainerGap(464, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("tab1", PanelRefugio);

        SigInsegura.setText("Siguiente");
        SigInsegura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SigInseguraActionPerformed(evt);
            }
        });

        AtrasRefugio.setText("Atrás");
        AtrasRefugio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasRefugioActionPerformed(evt);
            }
        });

        jLabel2.setText("Tunel 1");

        jLabel7.setText("Túneles");

        jLabel8.setText("Tunel 3");

        jLabel9.setText("Tunel 4");

        jLabel10.setText("Tunel 2");

        javax.swing.GroupLayout PanelTunelLayout = new javax.swing.GroupLayout(PanelTunel);
        PanelTunel.setLayout(PanelTunelLayout);
        PanelTunelLayout.setHorizontalGroup(
            PanelTunelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTunelLayout.createSequentialGroup()
                .addGroup(PanelTunelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelTunelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AtrasRefugio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SigInsegura))
                    .addGroup(PanelTunelLayout.createSequentialGroup()
                        .addGroup(PanelTunelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelTunelLayout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jScrollPaneTunel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPaneTunel2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPaneTunel4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPaneTunel3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelTunelLayout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(jLabel2)
                                .addGap(168, 168, 168)
                                .addComponent(jLabel10)
                                .addGap(166, 166, 166)
                                .addComponent(jLabel8)
                                .addGap(154, 154, 154)
                                .addComponent(jLabel9)))
                        .addGap(0, 167, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(PanelTunelLayout.createSequentialGroup()
                .addGap(428, 428, 428)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelTunelLayout.setVerticalGroup(
            PanelTunelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTunelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(PanelTunelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelTunelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneTunel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelTunelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPaneTunel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPaneTunel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPaneTunel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(PanelTunelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SigInsegura)
                    .addComponent(AtrasRefugio)))
        );

        jTabbedPane1.addTab("tab2", PanelTunel);

        AtrasTunel.setText("Atrás");
        AtrasTunel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasTunelActionPerformed(evt);
            }
        });

        jLabel3.setText("Zona Insegura");

        jLabel11.setText("Zona 1");

        jLabel12.setText("Zona 2");

        jLabel13.setText("Zona 3");

        jLabel14.setText("Zona 4");

        javax.swing.GroupLayout PanelZonaInseguraLayout = new javax.swing.GroupLayout(PanelZonaInsegura);
        PanelZonaInsegura.setLayout(PanelZonaInseguraLayout);
        PanelZonaInseguraLayout.setHorizontalGroup(
            PanelZonaInseguraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelZonaInseguraLayout.createSequentialGroup()
                .addGroup(PanelZonaInseguraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelZonaInseguraLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AtrasTunel))
                    .addGroup(PanelZonaInseguraLayout.createSequentialGroup()
                        .addGap(406, 406, 406)
                        .addComponent(jLabel3))
                    .addGroup(PanelZonaInseguraLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(PanelZonaInseguraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelZonaInseguraLayout.createSequentialGroup()
                                .addComponent(jScrollPaneInsegura1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPaneInsegura2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPaneInsegura3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPaneInsegura4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelZonaInseguraLayout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(jLabel11)
                                .addGap(168, 168, 168)
                                .addComponent(jLabel12)
                                .addGap(166, 166, 166)
                                .addComponent(jLabel13)
                                .addGap(154, 154, 154)
                                .addComponent(jLabel14)))))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        PanelZonaInseguraLayout.setVerticalGroup(
            PanelZonaInseguraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelZonaInseguraLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(PanelZonaInseguraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelZonaInseguraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneInsegura1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelZonaInseguraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPaneInsegura2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPaneInsegura4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPaneInsegura3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(AtrasTunel)
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab3", PanelZonaInsegura);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, -1, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SigTunelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SigTunelActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_SigTunelActionPerformed

    private void SigInseguraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SigInseguraActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_SigInseguraActionPerformed

    private void AtrasRefugioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasRefugioActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_AtrasRefugioActionPerformed

    private void AtrasTunelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasTunelActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_AtrasTunelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MonitorSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MonitorSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MonitorSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MonitorSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MonitorSistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AtrasRefugio;
    private javax.swing.JButton AtrasTunel;
    private javax.swing.JPanel PanelRefugio;
    private javax.swing.JPanel PanelTunel;
    private javax.swing.JPanel PanelZonaInsegura;
    private javax.swing.JButton SigInsegura;
    private javax.swing.JButton SigTunel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPaneInsegura1;
    private javax.swing.JScrollPane jScrollPaneInsegura2;
    private javax.swing.JScrollPane jScrollPaneInsegura3;
    private javax.swing.JScrollPane jScrollPaneInsegura4;
    private javax.swing.JScrollPane jScrollPaneTunel1;
    private javax.swing.JScrollPane jScrollPaneTunel2;
    private javax.swing.JScrollPane jScrollPaneTunel3;
    private javax.swing.JScrollPane jScrollPaneTunel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JScrollPane scrollPaneComedor;
    private javax.swing.JScrollPane scrollPaneComun;
    private javax.swing.JScrollPane scrollPaneDescanso;
    // End of variables declaration//GEN-END:variables
}
